arango:
  databaseName: spidergram
  url: http://127.0.0.1:8529
  auth:
    username: root
    password: ''

spider:
  userAgent: MyCustomSpider
  urlOptions:
    regions:
      - header
      - footer
      - body
  downloadMimeTypes:
    - application/pdf

urlNormalizer:
  discardTrailingSlash: true
