version: '3.7'
services:
  arangodb_container:
    image: arangodb/arangodb:3.10.2
    restart: unless-stopped
    environment:
      ARANGO_NO_AUTH: 1 
    ports:
      - 8529:8529
    volumes:
      - ./storage/arango:/var/lib/arangodb3
